--- 
docker-build: 
  script: 
      - "docker build -t registry.gitlab.com/chikelueoji/mta-hosting-optimizer ."
          - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"
	      - "docker push registry.gitlab.com/chikelueoji/mta-hosting-optimizer"
	        stage: package
		image: "docker:latest"
		k8s-deploy: 
		  image: google/cloud-sdk
		    script: 
		        - "echo \"$GOOGLE_KEY\" > key.json"
			    - "gcloud auth activate-service-account --key-file key.json"
			        - "gcloud config set compute/zone europe-west1-c"
				    - "gcloud config set project mta-hosting-optimizer"
				        - "gcloud config set container/use_client_certificate True"
					    - "gcloud container clusters get-credentials mta-hosting-optimizer"
					        - "kubectl delete secret registry.gitlab.com"
						    - "kubectl create secret docker-registry registry.gitlab.com --docker-server=https://registry.gitlab.com --docker-username=chikelueoji --docker-password=$REGISTRY_PASSWD --docker-email=chike_oji@yahoo.com"
						        - "kubectl apply -f deployment.yml"
							  stage: deploy
							  maven-build: 
							    artifacts: 
							        paths: 
								      - target/*.jar
								        image: "maven:3-jdk-8"
									  script: "mvn package -B"
									    stage: build
									    services: 
									      - "docker:dind"
									      stages: 
									        - build
										  - package
										    - deploy
										    variables: 
										      DOCKER_DRIVER: overlay
										        SPRING_PROFILES_ACTIVE: gitlab-ci

