apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mta-hosting-optimizer
  spec:
    replicas: 2
      template:
          metadata:
	        labels:
		        app: mta-hosting-optimizer
			    spec:
			          containers:
				        - name: mta-hosting-optimizer
					        image: registry.gitlab.com/chikelueoji/mta-hosting-optimizer
						        imagePullPolicy: Always
							        ports:
								        - containerPort: 8080
									      imagePullSecrets:
									              - name: registry.gitlab.com
